### ISSUE TITLE
Great image, can be successfully combined with Syncthing

### ISSUE THREAD

**Issue by lucwastiaux** [potz/docker-ergodox-ez-compiler#1]
Thanks for putting together this image. I've found that I can combine your image with a https://syncthing.net/ image in order to copy the keymap.c and resulting hex file back and forth between machines. This allows me to effectively compile an ergodox keymap on the cloud, and have the hex file delivered straight to a directory on windows without me lifting a finger.

**Comment by potz** [comment]
Heaven't heard about this syncthing but glad it helps.
